name: 'Build and Package .NET Library with Rust Native Binaries'
description: 'Builds and packages a .NET library, incorporating pre-downloaded native binaries for specified targets.'
branding:
  icon: 'package'
  color: 'red'

inputs:
  artifact-prefix:
    description: 'Prefix for the artifact names to download'
    required: false
    default: 'C-Library-'
  csharp-project-path:
    description: 'Path to the C# project directory'
    required: false
    default: 'bindings/csharp'
  install-dotnet:
    description: 'If true, installs the .NET SDK with specified version'
    required: false
    default: 'false'
  dotnet-version:
    description: 'Version of the .NET SDK to install'
    required: false
    default: '8.0.x'
  nuget-artifact-name:
    description: 'Name for the NuGet artifact'
    required: false
    default: 'NuGet-Package'

runs:
  using: 'composite'
  steps:
    - name: Install .NET Core SDK
      if: ${{ inputs.install-dotnet == 'true' }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Download Artifacts with Prefix
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.artifact-prefix }}*
        path: downloaded_artifacts/

    - name: Organize Artifacts
      shell: bash
      run: |
        tree "downloaded_artifacts/"
        TARGETS=(
          "x86_64-unknown-linux-gnu"
          "i686-unknown-linux-gnu"
          "aarch64-unknown-linux-gnu"
          "armv7-unknown-linux-gnueabihf"
          "x86_64-pc-windows-msvc"
          "i686-pc-windows-msvc"
          "aarch64-pc-windows-msvc"
          "x86_64-apple-darwin"
          "aarch64-apple-darwin"
          "x86_64-linux-android"
          "aarch64-linux-android"
          "armv7-linux-androideabi"
          "i686-linux-android"
          "aarch64-apple-ios"
          "x86_64-apple-ios"
        )

        for TARGET in "${TARGETS[@]}"; do
          case "$TARGET" in
            x86_64-unknown-linux-gnu)
              RUNTIME_ID="linux-x64"
              FILE_EXTENSION=".so"
              ;;
            i686-unknown-linux-gnu)
              RUNTIME_ID="linux-x86"
              FILE_EXTENSION=".so"
              ;;
            aarch64-unknown-linux-gnu)
              RUNTIME_ID="linux-arm64"
              FILE_EXTENSION=".so"
              ;;
            armv7-unknown-linux-gnueabihf)
              RUNTIME_ID="linux-arm"
              FILE_EXTENSION=".so"
              ;;
            x86_64-pc-windows-msvc)
              RUNTIME_ID="win-x64"
              FILE_EXTENSION=".dll"
              ;;
            i686-pc-windows-msvc)
              RUNTIME_ID="win-x86"
              FILE_EXTENSION=".dll"
              ;;
            aarch64-pc-windows-msvc)
              RUNTIME_ID="win-arm64"
              FILE_EXTENSION=".dll"
              ;;
            x86_64-apple-darwin)
              RUNTIME_ID="osx-x64"
              FILE_EXTENSION=".dylib"
              ;;
            aarch64-apple-darwin)
              RUNTIME_ID="osx-arm64"
              FILE_EXTENSION=".dylib"
              ;;
            x86_64-linux-android)
              RUNTIME_ID="android-x64"
              FILE_EXTENSION=".so"
              ;;
            aarch64-linux-android)
              RUNTIME_ID="android-arm64"
              FILE_EXTENSION=".so"
              ;;
            armv7-linux-androideabi)
              RUNTIME_ID="android-arm"
              FILE_EXTENSION=".so"
              ;;
            i686-linux-android)
              RUNTIME_ID="android-x86"
              FILE_EXTENSION=".so"
              ;;
            aarch64-apple-ios)
              RUNTIME_ID="ios-arm64"
              FILE_EXTENSION=".dylib"
              ;;
            x86_64-apple-ios)
              RUNTIME_ID="ios-x64"
              FILE_EXTENSION=".dylib"
              ;;
          esac

          # Create the target directory
          mkdir -p "${{ inputs.csharp-project-path }}/runtimes/$RUNTIME_ID/native"

          # Move only the specified file types into the correct runtime directory
          find downloaded_artifacts/ -type f -path "*/*$TARGET*/*$FILE_EXTENSION" -exec mv {} "${{ inputs.csharp-project-path }}/runtimes/$RUNTIME_ID/native/" \;
        done
        tree "${{ inputs.csharp-project-path }}/runtimes"

    - name: Build .NET Project
      shell: bash
      run: |
        cd "${{ inputs.csharp-project-path }}"
        dotnet build -c Release

    - name: Pack .NET Project
      shell: bash
      run: |
        cd "${{ inputs.csharp-project-path }}"
        dotnet pack -c Release --output nupkg/

    - name: Upload NuGet Package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.nuget-artifact-name }}
        path: |
          ${{ inputs.csharp-project-path }}/nupkg/*.nupkg
          ${{ inputs.csharp-project-path }}/nupkg/*.snupkg